### ISSUE TITLE
3.10-dev does not compile on debian stretch

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyenv/pyenv#1943]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information: Debian 9
- [X] OS architecture: amd64
- [X] pyenv version: from today
- [X] Python version: 3.10-dev
- [X] C Compiler information: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

3.10-dev fails, 3.9.5 works (and openssl headers etc. are all there, 3.9.5 builds happily):

```
    stretch64: Cloning https://github.com/python/cpython...
    stretch64: Installing Python-3.10-dev...
    stretch64: ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?
    stretch64: 
    stretch64: Please consult to the Wiki page to fix the problem.
    stretch64: https://github.com/pyenv/pyenv/wiki/Common-build-problems
    stretch64: 
    stretch64: BUILD FAILED
    stretch64:  (Debian 9.13 using python-build 2.0.0)
    stretch64: Inspect or clean up the working tree at /tmp/python-build.20210523192724.32720
    stretch64: Results logged to /tmp/python-build.20210523192724.32720.log
    stretch64: 
    stretch64: Last 10 log lines:
    stretch64:  LD_LIBRARY_PATH=/tmp/python-build.20210523192724.32720/Python-3.10-dev ./python -E -m ensurepip \
    stretch64:          $ensurepip --root=/ ; \
    stretch64: fi
    stretch64: Looking in links: /tmp/tmp29k8m1s7
    stretch64: Processing /tmp/tmp29k8m1s7/setuptools-56.0.0-py3-none-any.whl
    stretch64: Processing /tmp/tmp29k8m1s7/pip-21.1.1-py3-none-any.whl
    stretch64: Installing collected packages: setuptools, pip
    stretch64:   WARNING: The scripts pip3 and pip3.10 are installed in '/home/vagrant/.pyenv/versions/3.10-dev/bin' which is not on PATH.
    stretch64:   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    stretch64: Successfully installed pip-21.1.1 setuptools-56.0.0
    stretch64: Downloading Python-3.9.5.tar.xz...
    stretch64: -> https://www.python.org/ftp/python/3.9.5/Python-3.9.5.tar.xz
    stretch64: Installing Python-3.9.5...
    stretch64: Installed Python-3.9.5 to /home/vagrant/.pyenv/versions/3.9.5
```
